version: "3"

include:
  - docker-compose-services.yml

services:
  goose-hub-authentication-api:
    image: navatusein/goose-hub-authentication-api:latest
    container_name: authentication-api
    volumes:
      - host-volume:/app/appsettings.json
      - host-volume:/app/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
  
  goose-hub-user-profile-api:
    image: navatusein/goose-hub-user-profile-api:latest
    container_name: user-profile-api
    volumes:
      - host-volume:/app/appsettings.json
      - host-volume:/app/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  goose-hub-movie-api:
    image: navatusein/goose-hub-movie-api:latest
    container_name: movie-api
    volumes:
      - host-volume:/app/appsettings.json
      - host-volume:/app/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  goose-hub-comment-api:
    image: navatusein/goose-hub-comment-api:latest
    container_name: comment-api
    volumes:
      - host-volume:/app/appsettings.json
      - host-volume:/app/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  goose-hub-upload-api:
    image: navatusein/goose-hub-upload-api:latest
    container_name: upload-api
    volumes:
      - host-volume:/app/appsettings.json
      - host-volume:/app/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  goose-hub-video-processing-service:
    image: navatusein/goose-hub-video-processing-service:latest
    container_name: video-processing-service
    volumes:
      - host-volume:/app/appsettings.json
      - host-volume:/app/Logs
    restart: unless-stopped
  
  goose-hub-frontend:
    image: navatusein/goose-hub-frontend:latest
    container_name: frontend
    environment:
      - MY_APP_API_URL=https://example.com/api
      - MY_APP_ENVIRONMENT=Development
      - MY_APP_CONTENT_CAROUSEL_IDS=65f4ae2ead787fc1e52d0d93,663a4dde61755ee5f0e1579e,663a6d2dcb4f5ebceccee018,663a7019cb4f5ebceccee025
    restart: unless-stopped